### ISSUE TITLE
Upload extension to open-vsx.org

### ISSUE THREAD

**Issue by mmailaender** [selemondev/vscode-shadcn-svelte#8]
Could you please also upload that extension to open-vsx.org? So all people that are using a forked VScode version (e.g. Gitpod) can also install your extension 🙂

The steps needed are described here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

There is also a GitHub Action: https://github.com/HaaLeo/publish-vscode-extension#readme

**Comment by jokroese** [comment]
Could I help at all with moving this forward? Would love to use vscode-shadcn-svelte in my code editor, VSCodium :)

**Comment by selemondev** [comment]
Hey @jokroese, yes you can 😁.
